version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enterprise_hms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  orthanc:
    image: orthancteam/orthanc
    profiles:
      - pacs
    ports:
      - "8042:8042"
      - "4242:4242"
    environment:
      - ORTHANC_NAME=EnterpriseHMS-PACS
    volumes:
      - orthanc_data:/var/lib/orthanc/db

  ohif:
    image: ohif/viewer:latest
    profiles:
      - pacs
    ports:
      - "3000:80"

volumes:
  postgres_data:
  orthanc_data:
